export './onBoardingWidgets/onboarding_widget.dart';
export './accountWidgets/accountWidgets.dart';
export './animationWidget/animationWidgets.dart';
export './chatScreenWidgets/chatScreenWidgets.dart';
export './pageScreenWidgets/pageScreenWidgets.dart';
export './profileScreenWidgets/profileScreenWidgets.dart';
export './peopleScreenWidgets/peopleScreenWidgets.dart';
export './searchWidget/searchWidgets.dart';
export './homeScreenWidgets/homeScreenWidgets.dart';
